name: .NET Core

on:
  push:
    branches: 
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
                 
    - name: Setting environment variables
      run: echo "ApiKey = ${ASPNETCORE_CMS_CloudinarySettings__ApiKey} | Secret = ${ASPNETCORE_CMS_CloudinarySettings__ApiSecret} | cloudname = ${ ASPNETCORE_CMS_CloudinarySettings__CloudName} | Conn = ${ASPNETCORE_CMS_ConnectionStrings__DefaultConnection} | slack = ${ASPNETCORE_CMS_SlackSettings__Url}"
      env:
        ASPNETCORE_ENVIRONMENT: Production
        ASPNETCORE_CMS_CloudinarySettings__ApiKey: ${{ secrets.CloudinaryApiKey }}
        ASPNETCORE_CMS_CloudinarySettings__ApiSecret: ${{ secrets.CloudinaryApiSecret }}
        ASPNETCORE_CMS_CloudinarySettings__CloudName: ${{ secrets.CloudinaryCloudName }}
        ASPNETCORE_CMS_ConnectionStrings__DefaultConnection: ${{ secrets.ConnectionString }}
        ASPNETCORE_CMS_SlackSettings__Url: ${{ secrets.SlackSettingsUrl}}
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: ""
          SOURCE: "CMS/bin/Release"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/CMSarmatys"
