name: .NET Core

on:
  push:
    branches: 
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: TEST set env
      uses: allenevans/set-env@v1.0.0
      with:
          MY_ENV_VAR: 'my value'
          ASPNETCORE_CMS_CloudinarySettings:ApiKey: ${{ secrets.CloudinaryApiKey }}

    - name: TEST print env
      run: |
          echo "MY_ENV_VAR=${MY_ENV_VAR}"
          echo "CloudAPI=${ASPNETCORE_CMS_CloudinarySettings:ApiKey}"
          printenv
          
    - name: Setting environment variables
      run: echo "Ustawione > ${ASPNETCORE_CMS_CloudinarySettings:ApiKey} | Drugi parametr > ${TestEnv}"
      env:
        TestEnv: testvalue
        ASPNETCORE_ENVIRONMENT: Production
        ASPNETCORE_CMS_CloudinarySettings:ApiKey: ${{ secrets.CloudinaryApiKey }}
        ASPNETCORE_CMS_CloudinarySettings:ApiSecret: ${{ secrets.CloudinaryApiSecret }}
        ASPNETCORE_CMS_CloudinarySettings:CloudName: ${{ secrets.CloudinaryCloudName }}
        ASPNETCORE_CMS_ConnectionStrings:DefaultConnection: ${{ secrets.ConnectionString }}
        ASPNETCORE_CMS_SlackSettings:Url: ${{ secrets.SlackSettingsUrl}}
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: ""
          SOURCE: "CMS/bin/Release"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/CMSarmatys"
